### ISSUE TITLE
wrong attribute name

### ISSUE THREAD

**Issue by khanifzyen** [sintret/yii2-gii-adminlte#2]
thank you for this wonderful repo combined with yii2-basic-sintret

there is small bug, 
1. When creating crud with models consist of attibute contained data type date, it result wrong attribute name. it is always returning attribute 'release'
2. In model template it still use yii1 style for beforeSave, please use yii2 style with class yii\behaviors\BlamableBehavior and yii\behaviors\TimestampBehavior

**Comment by sintret** [comment]
I just fixed small bug in this repo. 
Please feels free to try again.

thanks
