### ISSUE TITLE
Error crud generator

### ISSUE THREAD

**Issue by dscuderi** [sintret/yii2-gii-adminlte#3]
Hi. We use advanced template and where generate the crud show error "The 'dynagrid' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\dynagrid\Module'." Sorry for my english. Thanks for you help

**Comment by sintret** [comment]
Hi , 

Like error shown, your application must be setup in your config, like this following url : 
http://www.yiiframework.com/extension/yii2-dynagrid/

```
'modules' => [
   'dynagrid' =>  [
        'class' => '\kartik\dynagrid\Module',
        // other settings (refer documentation)
    ],
    'gridview' =>  [
        'class' => '\kartik\grid\Module',
        // other module settings
    ],
],
```

**Comment by dscuderi** [comment]
it's works. Thanks!
